sap.ui.define([],
    function() {
        'use strict';
    
        var constants = {
            INTZERO: 0,
            INTONE: 1,
            INTFIVE: 5,
            INTSIX: 6,
            INTSEVEN: 7,
            INTNINE:9,
            INTTHOUS:1000,
            INTSIXTY:60,
            INTTEN:10,
            INTNEGONE: -1,
            INT412:412,
            ZERO:'0',
            DIV:":",
            SPACE:" ",
            spliter:";",
            httpPost: "POST",
            httpGet: "GET",
            ERROR: "Error",
            NONE: "None",
            onDemand:"ONDEMAND",
            recursive:"RECURSIVE",
            checkData:"CHECKDATA",
            suspend:"SUSPEND",
            actionOK:"OK",
            pricingDate:"ONDEMANDDATE",
            emailCC:"EMAILCC",
            checkD:"ONDEMANDT",
            emailTo:"INCEMAILTO",
            filterCUSID:"Customer ID",
            filterSH:"Ship-to",
            filterName:"Customer Name",
            pathCus:"Customer",
            suspended:"Suspended",
            timezone:"America/Mexico_City",
            pathCName:"CustomerName",
            pathSH:"ShipTo",
            pathSH2:"Shipto",
            pathSHName:"ShipToName",
            pathSHName2:"ShiptoName",
            pathTer:"Terminal",
            pathTername:"Terminalname",
            pathTName:"TerminalName",
            pathProd:"Product",
            pathProdName:"ProductName",
            prodID:"Product ID",
            prodName:"Product Name",
            terID:"Terminal ID",
            terName:"Terminal Name",
            dateError:"Enter a valid date",
            errormsgrequired:"Kindly fill the mandatory fields to proceed",
            errorInp:"Kindly correct the input to proceed",
            fragmentCusVH:"demo.app.fragments.CustomerListVH",
            fragmentProdF4:"demo.app.fragments.productF4",
            fragmentCusTablePopout:"demo.app.fragments.tablePopout",
            fragmentProdTablePopout:"demo.app.fragments.tableProdPopout",
            fragmentTerTablePopout:"demo.app.fragments.tableTerPopout",
            fragmentEmailPopover:"demo.app.fragments.emailPopover",
            fragmentProdPopover:"demo.app.fragments.productPopover",
            fragmentTerPopover:"demo.app.fragments.terminalPopover",
            fragmentAddTerminal:"demo.app.fragments.addTerminal",
            fragmentAddProd:"demo.app.fragments.addProduct",
            fragmentAddCCEmail:"demo.app.fragments.addEmailCc",
            fragmentAddDataIncCCEmail:"demo.app.fragments.addDataIncEmailCc",
            fragmentTerF4:"demo.app.fragments.terminalF4",
            fargmentCusF4:"demo.app.fragments.customerF4",
            fragmentProdVH:"demo.app.fragments.productListVH",
            fragmentTerVH:"demo.app.fragments.terminalListVH"
        };
        return constants;
    });