module.exports=Object.freeze({
    CLIENT_ID: '',
    CLIENT_SECRET: '',
    CLIENT_URL:'',
    ERROR: "Error",
    NONE: "None",
    onDemand:'ONDEMAND',
    daily:'RECURSIVE',
    suspendTo:'SUSPENDTO',
    suspendFrom:'SUSPENDFROM',
    jobNAME:'devSpaceJob',
    preURL:'Basic ',
    LOG_JS_API:'Successfully called REST api of Jobscheduler',
    LOG_JS_ERR:'Error occurred while calling REST api of Jobscheduler',
    SUCCESS:"Mail sent Successfully",
    SUCCESS_DEL:"Successfully Deleted",
    SUCCESS_EDIT:"Successfully Updated",
    LOG_SCH_DEL:"Schedule Deactivated",
    LOG_JS_DEL:"Schedule Deleted",
    LOG_JS_SUCC:'Successfully hitting to jobschedular',
    INTTWO:200,
    ERR:401,
    INTTW:201,
});